select * from customer;
-- Q1. What is the total revenue generated by male vs female customers? 
SELECT 
    gender, SUM(purchase_amount) AS revenue
FROM
    customer
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT 
    customer_id, purchase_amount
FROM
    customer
WHERE 
    discount_applied = 'yes'
        AND purchase_amount >= (SELECT 
            AVG(purchase_amount)
        FROM
            customer)
            
-- Q3. Which are the top 5 product with highest average review rating?
SELECT 
    item_purchased,
    Round(AVG(review_rating),2) AS 'Average Product Rating'
FROM
    customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Q4. Compare the average purchase amounts between standard and express shipping.
SELECT 
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM
    customer
WHERE
    shipping_type IN ('standard' , 'express')
GROUP BY shipping_type

-- Q5. Do subscribed customers spend more ? compare average spend and total revenue 
-- between subscriber and non-subscriber.
SELECT 
    subscription_status,
    COUNT(customer_id) AS Total_customers,
    ROUND(AVG(purchase_amount), 2) AS Avg_purchase_amount,
    ROUND(SUM(purchase_amount), 2) AS Total_revenue
FROM
    customer
GROUP BY subscription_status
ORDER BY Total_revenue , Avg_purchase_amount DESC;

-- Q6.Which 5 product have the highest percentage of purchases with discount applied?
SELECT 
    item_purchased,
    ROUND(SUM(CASE
                WHEN discount_applied = 'yes' THEN 1
                ELSE 0
            END) / COUNT(*) * 100,
            2) AS discount_rate
FROM
    customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. segment customers into new, returning, and loyal based on 
-- their total number of previous purchases, and show the count  of each segment.
with customer_type as (
select customer_id, previous_purchases,
case
	when previous_purchases =1 then 'NEW'
    WHEN previous_purchases between 2 and 10 then 'returning'
    else  'Loyal'
    END AS customer_segment 
from customer 
)
select customer_segment, count(*) as "Number of customer"
from customer_type 
group by customer_segment

-- Q.8 What are the top 3 most purchased products within each category?
with item_counts as (
select category,item_purchased,count(customer_id) as total_orders,
Row_number() over (partition by category order by count(customer_id) DESC) as item_rank 
from customer 
group by category, item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank <=3

-- Q.9 Are customer who are repeat buyers (more than 5 previous purchases) also likely to subscrice?
SELECT 
    subscription_status, COUNT(customer_id) AS repeat_buyers
FROM
    customer
WHERE
    previous_purchases > 5
GROUP BY subscription_status

-- Q.10 what is the revenue contribution of each age group?
SELECT 
    age_group, SUM(purchase_amount) AS total_revenue
FROM
    customer
GROUP BY age_group
ORDER BY total_revenue DESC;
